/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdp1_guesswordcw;

import java.io.*;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author HuSsAiN
 */
public class SDP1_GuessWorkCW extends javax.swing.JFrame {
    /**
     * Creates new form SDP1_GuessWorkCW
     */
    public SDP1_GuessWorkCW() {
        initComponents();
        
        limitLabel();
        ImageIcon defaultGuessWord = new ImageIcon(getClass().getResource("GuessWord1.png"));
        btn_img.setIcon(defaultGuessWord);
        btn_img.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_img = new javax.swing.JButton();
        btn_tryLetter = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        txt_GuessLetter = new javax.swing.JTextField();
        lbl_inco = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        lbl_times = new javax.swing.JLabel();
        lblChar1 = new javax.swing.JLabel();
        lblChar2 = new javax.swing.JLabel();
        lblChar3 = new javax.swing.JLabel();
        lblChar4 = new javax.swing.JLabel();
        lblChar5 = new javax.swing.JLabel();
        lblChar6 = new javax.swing.JLabel();
        lblChar7 = new javax.swing.JLabel();
        lblChar8 = new javax.swing.JLabel();
        lblChar9 = new javax.swing.JLabel();
        lblChar10 = new javax.swing.JLabel();
        lbl_hint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman Game!");
        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imgActionPerformed(evt);
            }
        });

        btn_tryLetter.setText("Try Letter");
        btn_tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tryLetterActionPerformed(evt);
            }
        });

        btn_quit.setText("Quit");
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });

        txt_GuessLetter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_GuessLetterKeyTyped(evt);
            }
        });

        lbl_inco.setText("Incorrect Value:-");

        lblCount.setText("0");

        lbl_times.setText("/ 6");

        lblChar1.setText("X");

        lblChar2.setText("X");

        lblChar3.setText("X");

        lblChar4.setText("X");

        lblChar5.setText("X");

        lblChar6.setText("X");

        lblChar7.setText("X");

        lblChar8.setText("X");

        lblChar9.setText("X");

        lblChar10.setText("X");

        lbl_hint.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbl_hint.setText("Hint: Car Brand Names..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hint)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_GuessLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_inco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCount))
                                            .addComponent(btn_tryLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_times)
                                            .addComponent(btn_quit)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblChar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChar10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_img, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChar1)
                            .addComponent(lblChar2)
                            .addComponent(lblChar3)
                            .addComponent(lblChar4)
                            .addComponent(lblChar5)
                            .addComponent(lblChar6)
                            .addComponent(lblChar7)
                            .addComponent(lblChar8)
                            .addComponent(lblChar9)
                            .addComponent(lblChar10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_GuessLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_inco)
                            .addComponent(lblCount)
                            .addComponent(lbl_times))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tryLetter)
                            .addComponent(btn_quit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_img, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hint))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public List wordList = new ArrayList();
    public String word;
    public int incorrectGuessCount = 0;
    public int correctGuessCount = 0;
    
    public void readFile(){
        try{
            File f = new File("E:\\IIT\\1st Year\\SDP1\\CW1\\SDP1_GuessWordCW\\src\\sdp1_guesswordcw\\words.txt");
            Scanner readFile = new Scanner(f);
            while(readFile.hasNext()){
                wordList.add(readFile.next().toLowerCase());
            }
        }catch(FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
}
    public void setWordLetter(){
        int RandomWordList =(int)(Math.random() * 6);  
        word = wordList.get(RandomWordList).toString().toLowerCase();
    }
    private void btn_tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tryLetterActionPerformed
        char[] eachCharc = new char[10];
        int countEachCharc =0;
        while (countEachCharc<word.length()){
            eachCharc[countEachCharc] = word.charAt(countEachCharc);
            countEachCharc++;
        }
        try{
        int count=0;          
        char guessedCharc = txt_GuessLetter.getText().charAt(0);
        for(int i = 0;i < word.length();i++){
            if(guessedCharc == eachCharc[i]){
            switch (i) {
                case 0:
                    lblChar1.setText(""+guessedCharc);
                    break;
                case 1:
                    lblChar2.setText(""+guessedCharc);
                    break;                   
                case 2:
                    lblChar3.setText(""+guessedCharc);
                    break;
                case 3:
                    lblChar4.setText(""+guessedCharc);
                    break;
                case 4:
                    lblChar5.setText(""+guessedCharc);
                    break;
                case 5:
                    lblChar6.setText(""+guessedCharc);
                    break;
                case 6:
                    lblChar7.setText(""+guessedCharc);
                    break;
                case 7:
                    lblChar8.setText(""+guessedCharc);
                    break;
                case 8:
                    lblChar9.setText(""+guessedCharc);
                    break;
                case 9:
                    lblChar10.setText(""+guessedCharc);
                    break;
                default:
            }
                correctGuessCount++;
            }else{
                count++;
            }
        }
         txt_GuessLetter.setText("");
        if (count == word.length()){
            incorrectGuessCount++;
            lblCount.setText("" + (incorrectGuessCount));
        }
        if(correctGuessCount == word.length()){
            JOptionPane.showMessageDialog(rootPane, "Congratzz you have won. Game over.", "Congratulations! :D", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
        } 
        }catch(Exception ee){
           JOptionPane.showMessageDialog(rootPane, "Enter a Letter", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        switch (incorrectGuessCount) {
            case 1:
                ImageIcon guessWord1 = new ImageIcon(getClass().getResource("GuessWord2.png"));
                btn_img.setIcon(guessWord1);
                break;
            case 2:
                ImageIcon guessWord2 = new ImageIcon(getClass().getResource("GuessWord3.png"));
                btn_img.setIcon(guessWord2);
                break;
            case 3:
                ImageIcon guessWord3 = new ImageIcon(getClass().getResource("GuessWord4.png"));
                btn_img.setIcon(guessWord3);
                break;
            case 4:
                ImageIcon guessWord4 = new ImageIcon(getClass().getResource("GuessWord5.png"));
                btn_img.setIcon(guessWord4);
                break;
            case 5:
                ImageIcon guessWord5 = new ImageIcon(getClass().getResource("GuessWord6.png"));
                btn_img.setIcon(guessWord5);
                break;
            case 6:
                ImageIcon guessWord6 = new ImageIcon(getClass().getResource("GuessWord7.png"));
                btn_img.setIcon(guessWord6);
                lbl_hint.setText(word);
                JOptionPane.showMessageDialog(rootPane, "You did not win. Game over.", "You Lost!", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
            default:
                break;
        }
       
    }//GEN-LAST:event_btn_tryLetterActionPerformed

    private void btn_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imgActionPerformed
    }//GEN-LAST:event_btn_imgActionPerformed
    
    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        int quit = JOptionPane.showConfirmDialog(null,"Are you sure you want to quit?","Quit game",JOptionPane.YES_NO_OPTION);
            if (quit == JOptionPane.YES_OPTION){
                System.exit(0);
            }
    }//GEN-LAST:event_btn_quitActionPerformed
    private void txt_GuessLetterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GuessLetterKeyTyped
        if (txt_GuessLetter.getText().length() >=1){
            evt.consume();
        }
    }//GEN-LAST:event_txt_GuessLetterKeyTyped
    private void limitLabel() {
        readFile();
        setWordLetter();
        switch (word.length()) {
            case 3:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                lblChar8.setVisible(false);
                lblChar7.setVisible(false);
                lblChar6.setVisible(false);
                lblChar5.setVisible(false);
                lblChar4.setVisible(false);
                break;
            case 4:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                lblChar8.setVisible(false);
                lblChar7.setVisible(false);
                lblChar6.setVisible(false);
                lblChar5.setVisible(false);
                break;
            case 5:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                lblChar8.setVisible(false);
                lblChar7.setVisible(false);
                lblChar6.setVisible(false);
                break;
            case 6:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                lblChar8.setVisible(false);
                lblChar7.setVisible(false);
                break;
            case 7:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                lblChar8.setVisible(false);
                break;
            case 8:
                lblChar10.setVisible(false);
                lblChar9.setVisible(false);
                break;
            case 9:
                lblChar10.setVisible(false);
                break;
                default:
                break;
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDP1_GuessWorkCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDP1_GuessWorkCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDP1_GuessWorkCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDP1_GuessWorkCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDP1_GuessWorkCW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_img;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_tryLetter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChar1;
    private javax.swing.JLabel lblChar10;
    private javax.swing.JLabel lblChar2;
    private javax.swing.JLabel lblChar3;
    private javax.swing.JLabel lblChar4;
    private javax.swing.JLabel lblChar5;
    private javax.swing.JLabel lblChar6;
    private javax.swing.JLabel lblChar7;
    private javax.swing.JLabel lblChar8;
    private javax.swing.JLabel lblChar9;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lbl_hint;
    private javax.swing.JLabel lbl_inco;
    private javax.swing.JLabel lbl_times;
    private javax.swing.JTextField txt_GuessLetter;
    // End of variables declaration//GEN-END:variables
}
